trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: FirstJob
  steps:
  - script: echo Ugobase first commit!
    displayName: 'Run a one-line script'
- job: SecondJob
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo run tasks
    displayName: 'Run a multi-line script'
  - script:
      echo Second Job
      echo Runtime
    displayName: 'Run a multi-line script'
    
