trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: FirstJob
  steps:
  - script: echo Ugobase first job!
    displayName: 'Run a one-line script'
- job: SecondJob
  dependsOn: FirstJob
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo run tasks
    displayName: 'Run a multi-line script'
  - script:
      echo Second Job!
      echo Run this code!
    displayName: 'Run a multi-line script'
- job: ThirdJob
  dependsOn:
  - FirstJob
  - SecondJob
  steps:
  - script:
      echo Update Third Job!
      echo Run update
      echo Push Job!
    displayName: 'Run a multi-line script'