trigger:
- main

#pool:
  vmImage: ubuntu-latest

Stages:
- stage: Build
  jobs:
  - job: FirstBuild
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: echo first build!
  - job: SecondBuild
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash:
        echo second build
        echo run
- stage: Prod
  dependsOn: Build
  jobs:
  - job: FirstDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: 
        echo first deployment!
        echo run deployment
  - job: SecondDeploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: 
        echo second deployment!
        echo run deployment
- stage: Test
  dependsOn: 
    Build
    Prod
  jobs:
  - job: FirstTest
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: 
        echo first test!
        echo run test
  - job: SecondTest
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: 
        echo second test!
        echo run test
