trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstBuild
    variables:
      server: EC2
    steps:
    - bash: echo build first job!
    - bash: echo $(server)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SoucesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'System.DefaultWorkingDirectory'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: 'Build.ArtifactStagingDirectory'
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Ugobase'
        publishLocation: 'Container'