trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstBuild
    steps:
    - bash: echo First Build
    displayName: 'Run a one-line script'

- stage: DevDeploy
  jobs:
    - deployment: FirstBuild
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo deploy to dev

- stage: TestDeploy
  jobs:
    - deployment: FirstBuild
      environment: Test
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo deploy to test